-- Deploy agendum:user to pg

BEGIN;

-- Table to store person details
CREATE TABLE person (
    person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identity-based primary key
    public_id TEXT NOT NULL UNIQUE, -- Shared ID across systems
    email TEXT NOT NULL UNIQUE, -- Email from ID token
    given_name TEXT, -- First name
    family_name TEXT, -- Last name
    created_at TIMESTAMPTZ DEFAULT NOW(), -- Record creation timestamp
    updated_at TIMESTAMPTZ DEFAULT NOW() -- Record update timestamp
);

CREATE INDEX idx_person_public_id ON person(public_id);

-- Trigger for automatic 'updated_at' update on person
CREATE TRIGGER trigger_update_person_updated_at
BEFORE UPDATE ON person
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

COMMIT;