
BEGIN;

DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS state;
DROP TABLE IF EXISTS employment;

DROP TABLE IF EXISTS task_labels;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS labels;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS person;

COMMIT;
